### ISSUE TITLE
Introduce yourself

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-spring20#1]
Hi everyone - 

I thought I'd kick off a post where everyone can reply with an introduction to themselves so we can get to know each other. 

**Tell us what brought you to this course and any other details you care to share.**

A little bit about myself - I'm a web programmer and educator, living in Arlington, MA. In addition to this course, I also teach [DGMD E-2](/e2) and [CSCI E-15](https://hesweb.dev/e15). I've also worked with students completing their capstones in the DGMD program.

In the past, I've taught at Wellesley, UPenn, and UMiami. When working in industry I was the head developer for an online e-commerce store. 

More about my background here: [susanbuck.net](https://susanbuck.net)

All in all, I love creating things with code and teaching others how to do the same.

Looking forward to getting to know you all!

**Comment by angyts** [comment]
I’m Paul Ang, a family doctor in Singapore. 

I actually have my hands very full at the moment. 

![9BA90676-09F8-4097-B465-7EA955BF93B0](https://user-images.githubusercontent.com/23327200/72775573-eaee8200-3c49-11ea-8bbf-d202574c992c.jpeg)

I found out how busy I actually am, after I’ve decided that i’m going to take a masters in digital media in design at Harvard Extension School.

🤷‍♂️

My passion is in mental health, instructional design, digital media, family medicine and “making things with my own hands”.

**Comment by MatthewCaulkins** [comment]
Hi,

I'm a developer in Boston, originally front-end but steadily have been moving to full-stack.  I have worked with Angular and the MEAN stack, and figured Vue would be a good next step.

**Comment by ambielecki** [comment]
Hello,
I'm Andrew Bielecki, a software engineer living and working a little north of Boston, MA.  I've worked a little with Vue in the past, just a few small components here and there, but never had the chance or need for a full Vue SPA type application.

This is my final class for my masters in Information Management Systems at the Extension school, I took Susan's course e15 early on in the journey so I'm looking forward to an interesting final semester.

**Comment by BrendanJohn** [comment]
Hi,
I'm Brendan and I am a software engineer in Boston. Like Andrew, I also took Susan's awesome dwa-15 course many years ago (5 years?) and I'm pretty sure I remember your avatar Andrew, good to see you again. I have a few courses left in my Information Management Systems degree which I am hoping to finish off within a year. I don't know much about Vue.js, but I am looking forward to learning all about it and web components.

**Comment by BrendanJohn** [comment]
Hi,
I'm Brendan and I am a software engineer in Boston. Like Andrew, I also took Prof. Buck's awesome dwa-15 course many years ago (5 years?) and I'm pretty sure I remember your avatar Andrew, good to see you again. I have a few courses left in my Information Management Systems degree which I am hoping to finish off within a year. I don't know much about Vue.js, but I am looking forward to learning all about it and web components.

**Comment by ShBodden** [comment]
Hello,
I'm Shawn. I live in Boston and currently work as a network engineer in Cambridge. I came to the tech sector after a recent career change. The network side has been interesting but I really enjoy web programming and seeing ideas come to life. I hope this class will help me as I look to further my career in the direction I'd like. I previously took Dynamic Web Applications with prof. Buck a few years ago; I'm pretty sure Andrew was in class with me. 

Since working on the network side, I haven't done much programming and I hope to shake some of the rust off.

I look forward to "meeting" everyone!

**Comment by hakanovski** [comment]
Hello,

This is Hakan from Plano, TX. I have been working for Samsung Electronics America for more than 10 years as a senior SDET. I am working on testing and building automation frameworks for Android phones of Samsung. I am mainly working on Python for automation and C# on .NET framework (mostly WinForm and WPF) for tool and framework development purposes.

I am very excited about this class since I do not have an experience with Javascript and it is about web design. After 10 years of OOP and  script-base automation I think website development is more unique, fun and feels like more motivating for me. I feel like more creative while working on website development. 

I have taken 2 beautiful web design classes in HES so far. One of them was  David Heitmeyer's Fundamentals of Website Development long time back and Jen Kramer's Modern and Mobile Front-End Web Design I. This semester I am also taking the second part of this class.

I am sure with this class I will have a solid knowledge about Javascript, VueJS and I will have a better approach about website development.

**Comment by jaggedaz** [comment]
Hi!  I'm Josh and decided to take this class because I really enjoy working with JavaScript frameworks like Angular and React and thought I'd give Vue a try too.  I've been doing software development for about 15 years now and my passion is UX design and front-end development.  I'm excited about this class because I love learning about and experimenting with new technologies.

Glad to meet everyone and can't wait to get started!

**Comment by vthil3049** [comment]
Hi I'm Vani. I live and work in New Hampshire about an hour north of Boston. Having dealt with the traffic in Boston, I'm so glad this course is online 👍.  I took the CSCI E-15 class with Prof.Buck a few years ago and it was extremely helpful. I've been working with AngularJS, Angular and dabbled in the Ionic framework a bit. I'm eager to learn about Vue and other frameworks also through this course.

**Comment by guyewhite** [comment]
Hi Beautiful Team,

I'm Guy. I'm a father of four in Portland, Oregon. This is my fourth and final class in the Programming Certificate sequence at Harvard Extension. My full time gig is teaching doctoral dissertation writers how to finish. I'm planning on using what I learn in this course to create numerous single page apps for my business. It's exciting to know that what I'm learning in this course will be immediately impactful to my clients and family.

Thanks for the chance to say hi!

**Comment by procchio77** [comment]
Hi Everyone, 

I'm Patrick.  I am a manager of a small software team in downtown Boston.  I'm a father of two beautiful energetic kids, living in Arlington, MA.  I am here because I decided to get my Master's in Software Engineering or MIS - still have not decided.  It has been awhile since I have been hands on in the web dev stack, and I sorely miss it, so much so that I am heavily considering getting back into a dev role.  I am very excited for this class because I will finally get my feet wet with SPA development and I know the skills acquired here will be applied to projects in the pipeline. 

Looking forward to a wonderful semester with everyone!

**Comment by DoryAzar** [comment]
Hi All!

I'm Dory (yep that is my name). I work for a software company in the Boston area in the field of User Experience. I am getting a Master's in Digital Media Design. I have a background in computer engineering so programming is not new to me. I am very interested in learning VueJS so I am looking forward to this class. Other than that, I like traveling, running, fitness, skiing and believe it or not programming is another hobby of mine.

Can't wait to get this going!

**Comment by nbpandeti** [comment]
Hi All!

My name is Nitya. I am a senior software engineer work for Motorola in Alabama working on 911 call taking software. I'm mostly working with Java and MySQL. I haven't really been working on the front-end for the past couple of years, so I'm taking this course so that I can re-familiarize with the front-end and learn VueJS. 

I look forward to leaning with all of you!!

**Comment by maqboolk** [comment]
Hi All,

My name is Maqbool, and I work for Harvard University Information Technology, as a Software Quality Engineer. Our team is working on this application which is using VueJS and that is the main reason i am taking this class. I want to know more about Vue so I can test our application in efficient way. Also maybe i can write some unit tests for our application.

Good luck to everyone.
Maqbool

**Comment by franzparks** [comment]
Hello!
My name is Francis and I live in Santa Clara, CA and I work as a software engineer. I took this course to learn more about front-end development. I am also pursuing my masters in Software Engineering at HES. I look forward to learning with you all!

**Comment by csci50-cbutler** [comment]
Hi Everyone,

I am Cecilia Butler.  I live in the Bay Area.  I work in Palo Alto for a software company.  I took this course to be able to create and implement software that is more efficient.  We currently use MPA for most everything.  I am thinking this can help.  

On a personal note, I like product design and development.  I am hoping to create an online site one more technology focused and maybe another later for "hobbies".  I am hoping SPA can help me keep it updated.

Looking forward to learning VUE to do this.

Cecilia

**Comment by JoshGrosserhode** [comment]
Hello Everybody,

My name is Joshua Grosserhode. I currently live in the Seattle area, where I work for Boeing as an acoustic engineer. My most enjoyable projects at work have been developing small applications, so I decided to try switching careers from mechanical engineering to software. I am not very experienced yet, but I am excited to make this shift. Currently I am working on the Programming Certificate through HES.

**Comment by mohdmunsif** [comment]
Hi all.

I'm Mohd Munsif, currently working at Harvard IT as an Application developer. I am interested to learn more about JS frameworks (already took React course and tried using Angular a bit before) . Also, this course is part of completing a certification from HES. 

Looking forward to learning more about Vue in the next 12 weeks!

**Comment by lfilmeyer** [comment]
Hi all!

My name is Laura Filmeyer (nee Filman).  I’m a software engineer at LevelUp, which was acquired by Grubhub over a year ago.  I’ve been working in software for almost seven years now, six of which I’ve spent also taking classes through Harvard Extension!  This is my last class for my masters in Information Management Systems.  The very first class I took in Summer 2014 was e15 with Susan Buck, so I’m excited to be coming full circle now!  I’m also excited to be taking this class since it’ll be relevant at work, where some of our frontend is migrating to use React.  It’ll be nice to become more familiar with Javascript single page frameworks in general.

Also, hi @ambielecki! We were in the capstone class together last semester, hopefully you remember me! 👋

**Comment by ambielecki** [comment]
Good to see you again @lmfilman , it was definitely a good class last semester

**Comment by RobertHolzhauser** [comment]
Hello Everyone!  I'm Robert Holzhauser.  I live in Parker, Colorado, USA.  I'm fairly new as a full-stack developer (~ 1 year), I've taken about half a dozen cs courses through extension.  I'm really looking forward to learning Vue.js, I think it has a LOT of potential.

I'm excited to be here with you all.  Talk soon!

**Comment by smaaliki** [comment]
Hi Everyone! This is **Samer Maaliki**. 

I attended *Boston University* where I received a bachelor degree in Biomedical Engineering in 1998.  In 2000, I finished my Masters in the same subject at *University of Miami*.  

After a summer internship at NASA working on an arrhythmia detection algorithm, I got a job with Siemens in Danvers, MA working on developing algorithms for their Patient Monitors. In 2004 I moved to [Abiomed](http://www.abiomed.com/), also in Danvers, to work on algorithms for the artificial heart program and other cardiovascular devices.

In 2010, I moved with my family to Dubai and in 2014 I started working for the Government of Dubai as a Senior Consultant. The majority of my work now is working with vendors on developing different online portals/web applications for the government organizations here.  That is why in 2017 I started taking some courses through HES to learn more about web application development.

I took CSCI-E15 with Susan and I found it very helpful in learning how to build web applications.  I am interested in Vue as it seems that SPA are becoming more more prevalent and I can already see us using it in our systems.

**Comment by heidericklucas** [comment]
Hello everyone! I'm Lucas Vieira. I decided to take this course mainly because I enjoyed taking CSCI E-15 with Professor Susan Buck, I learned much more than I was expecting, so I'm sure this class will be no different in that sense.

I'm looking forward to acquiring new knowledge.

**Comment by Hawk31** [comment]
Hello everyone! My name is Hakeem Mance.  Im taking this course as part of the Front End Development certificate. The course description sounded interesting so I decided to enroll. I work for HUIT in Field Support and i'm working towards building my coding skills to Freelance. I look forward to working with everyone this semester and learning as much as possible!

**Comment by james-mathis** [comment]
Hello everyone! My name is James Mathis. I am taking this course in pursuit of learning more about JavaScript. The course description and teacher looks to be very challenging, and I can not wait to start on the bigger projects!
