### ISSUE TITLE
How can I run e2e specs in order.

### ISSUE THREAD

**Issue by maqboolk** [susanBuck/e28-spring20#101]
Hi all,
Does anyone know how to config e2e specs to make them run in certain order. 
They are running by spec names in ascending order. 
Maybe, I want to run in descending order or want to run 3rd and 4th spec before 1 and 2. 

Any Idea?

thanks

**Comment by susanBuck** [comment]
I don't believe there's a setting/official way to accomplish this, but you could prefix your spec names with a number. Because specs are run alphabetically, this would get the job done.

I'm assuming you want control of order because certain tests depend on data created in previous tests? If so, I do want to note that this isn't ideal. Each spec should be able to run independent of other specs.

The way to accomplish this is to have mechanisms in place that set up the data/state needed for a given test. 

A bare bones example of this can be accomplished with Cypress commands. This was something I showed in the bonus video I posted on authentication, so in case you didn't get a chance to see that, here's a run down:

In `tests/e2e/support/commands.js` you can define your own Cypress commands.

[Example from ZipFoods](https://github.com/susanBuck/e28/blob/master/zipfoods/tests/e2e/support/commands.js):

```js
// Regular user
let user = {
    name: 'Test User',
    email: 'user@email.com',
    password: 'asdfasdf'
}

// Admin user
let adminUser = {
    name: 'Susan Buck',
    email: 'susanbuck@fas.harvard.edu',
    password: 'asdfasdf'
}

Cypress.Commands.add('loginAsUser', () => {
    cy.logout();
    cy.visit('login');
    cy.get('[data-test=email-input]').type(user.email);
    cy.get('[data-test=password-input]').type(user.password);
    cy.get('[data-test=login-button]').click();
    cy.get('[data-test=logout-link]').should('exist');
})

Cypress.Commands.add('loginAsAdmin', () => {
    cy.logout();
    cy.visit('login');
    cy.get('[data-test=email-input]').type(adminUser.email);
    cy.get('[data-test=password-input]').type(adminUser.password);
    cy.get('[data-test=login-button]').click();
    cy.get('[data-test=logout-link]').should('exist');
})

Cypress.Commands.add('logout', () => {
    cy.visit('/e2e/logout');
    cy.contains('logout complete');
})
```

These commands could then be invoked to set up for different tests.

**Comment by maqboolk** [comment]
@susanBuck 
Thank you. 
I will organize my specs so they run independently.
