### ISSUE TITLE
Error setting up unit tests

### ISSUE THREAD

**Issue by tmussa1** [susanBuck/e28-spring20#107]
Hello All,

I am getting the error below trying to setup my unit test. And here is my repo https://github.com/tmussa1/p3. I really appreciate your help

```
TypeError: Cannot read property 'stringify' of undefined
    at Module../node_modules/@firebase/webchannel-wrapper/dist/index.esm.js (C:\Users\Tofik Mussa\Desktop\MS in CS\CSCI E-28\cscie-28\project3\flash-card-dictionary\dist\js\webpack:\node_modules\@firebase\webchannel-wrapper\dist\index.esm.js:21:1)
```

**Comment by susanBuck** [comment]
Testing on my end now.

**Comment by susanBuck** [comment]
I'm seeing some different errors when I run your unit tests.

The first error notes:

> [Vue warn]: Error in data(): "TypeError: Cannot read property 'params' of undefined"

This happens because the Game.vue SFC is attempting to reference $route:

```js
category: this.$route.params.category,
```

This is not available in the unit test, because the SFC is being mounted in isolation. To address, you can mock the $route data like so:

```js
const wrapper = shallowMount(Game, {
        mocks: {
            $route: {
                params: { category: 'Careers' }
            }
        }
    })
```



After addressing that, the next error states:

> [Vue warn]: Unknown custom element: <b-button-group> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

This error repeats for all your other bootstrap components. 

To address this, I found a section in the Vue testing docs on "[Applying Global Plugins and Mixins](https://vue-test-utils.vuejs.org/guides/#applying-global-plugins-and-mixins)":

![image](https://user-images.githubusercontent.com/237711/81958498-1a037780-95dc-11ea-8232-df40e7f5d152.png)

To implement this, I added the following six lines indicated by red arrows:

![image](https://user-images.githubusercontent.com/237711/81958665-4e773380-95dc-11ea-8aa1-6257302aa107.png)

After clearing that up, the next issue was:

> [Vue warn]: Error in mounted hook: "ReferenceError: localStorage is not defined"

This happens because localStorage is a browser feature and unit tests don’t use a browser. Testing localStorage functionality is something better suited for E2E testing.

It is possible to mock local storage, but it would be better if you decoupled the component from local storage - similar to how I did with Cart.js. That way, you could easily mock it for testing purposes.

On this note, you might rethink whether a unit test is most appropriate for the Game.vue SFC because it involves so many other pieces. For the purposes of this project, it might make more sense to build a unit test for one of your smaller/child components.

This isn't to say Game.vue can't/shouldn't have a unit test - it might just be more efficient/appropriate to address it with an E2E test.

**Comment by tmussa1** [comment]
Thank you and that was helpful. I was also having trouble mounting custom bootstrap compnents that I was using and found this post useful https://stackoverflow.com/questions/56499822/getting-vue-warn-unknown-custom-element-b-modal-even-though-bootstrap-vue. My tests are working fine now
