### ISSUE TITLE
View Quiz Questions Post Submission

### ISSUE THREAD

**Issue by procchio77** [susanBuck/e28-spring20#11]
Is it possible to view the assignment questions, prior to grading, after a submission without having to retake the quiz.  I submitted my assignment last Thursday and just wanted to review some notes about Project 1.

**Comment by susanBuck** [comment]
Hi @procchio77 - Unfortunately, I can't configure Canvas to let you see your answers post-submission, prior to grading. The reason is because there's no way to tell Canvas to not show you what answers you got incorrect, and using that information, a student could continue to re-take the assignment until no more answers were showing as incorrect.

You may be interested in checking out the [Chrome Full Page Screenshot](https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl?hl=en) plugin I referenced in the week 1 assignment as a way to take a snapshot of your assignment pre-submission to have on hand for reference. (If you use a browser other than Chrome, search your browser extensions marketplace - i'm sure there's equivalent plugins for other browsers).

Obviously not a solution for last week's assignment - so I'll send you an email with a copy of your assignment. 👍
