### ISSUE TITLE
Renaming "Schedule" ?

### ISSUE THREAD

**Issue by procchio77** [susanBuck/e28-spring20#20]
Don't ask me why, but I can remember most of the subject matter we are learning, but I cannot remember where the video lectures are.  Is it possible to rename "Schedule" to Lectures or akin? I am open to any other suggestions.  I can of course create my own bookmark, but I want to help out future victims, hopefully I am not the only one :)

**Comment by susanBuck** [comment]
For those reading this thread - can you weigh in on whether this is an issue you've also faced?

I'm open to suggestions/improvements, but would like to get a bit more feedback that it's a problem before making a change.

**Comment by DoryAzar** [comment]
I personally got used to it. I operate by location rather than name. As long as you don’t change the location, whatever you decide to call it works for me.

**Comment by ambielecki** [comment]
Schedule made as much sense as anywhere (I guess I could see where someone would just think it would be a static page, but I like having it all in one spot)

The only thing I continually have to search for is the quick link to the full notes site

**Comment by susanBuck** [comment]
@ambielecki - I can see what you mean about the quick link to the notes. 

I did some playing around with a redesign where the quick links are a) more explicit and b) integrated into the current semester heading (while still distinguished from other "in-site" links via the use of icons).

Thoughts?

Screenshot:
![image](https://user-images.githubusercontent.com/237711/75907076-b871a080-5e15-11ea-8424-36e3c49e521d.png)

**Comment by ambielecki** [comment]
Yeah, I like that.  The icons draw attention, but it really helps seeing the Notes text.  It's somewhere we end up fairly frequently (especially since the notes are nicely organized and easy to use once you're there)

**Comment by ambielecki** [comment]
Will there be a note archive available after the semester?  I still find my self referencing the DWA15 notes that I forked on github occasionally (one of these days I'll remember the command to generate ssh keys).

**Comment by susanBuck** [comment]
Cool, glad that design clicks better 👍I'll wait a bit to see if any other students have feedback before deploying these changes.

**re: archive:** Yup! At the end of the semester I'll provide students with a zip file of all code examples (i.e. my `e28` repository), all the notes, and also an archive of the forum posts.

(The only thing not included in the archive is the lecture videos which - per HES policy - are only available for 3 months after the end of the semester.)

(I also refer to my own notes any time I have to generate SSH keys; one of these days I'll create a shortcut. : )

**Comment by RobertHolzhauser** [comment]
I like the names next to the icons.  Makes it a little easier to find my way to where I want to go.
Thanks!

**Comment by maqboolk** [comment]
New design looks good. It will be great if they always open in new tab. I don't like when they loads in same page and then i have to go back to see something else 
I have been opening them(Notes, Forum, and canvass) in new tab using right click every time so i don't have to go back.

**Comment by susanBuck** [comment]
Glad you like the new design, @maqboolk and @RobertHolzhauser 👍

@maqboolk - Whether or not to open links in new tabs is a common debate/topic in UI/UX. : )

I prefer letting links have their default behavior (opening in same tab) because while it's easy for a "tab preferred" user to get their desired behavior, a "same window preferred" user can't work around links that are set to open in new tabs.

There are also other sound arguments against opening links in new tabs (accessibility, mobile experience, etc.) For more on this, check out: https://uxdesign.cc/linking-to-a-new-tab-vs-same-tab-f88b495d2187

I recommend getting comfortable with a keyboard shortcut to open links in new tabs. For example on Mac/Chrome, if I hold down command while clicking a link, it opens in a new tab. Shaves a few seconds off the process of right-clicking and choosing the menu option.

**Comment by procchio77** [comment]
The new design works for me.
