### ISSUE TITLE
.push into an array, single object seems fine, but array only store the last entry with multiple times

### ISSUE THREAD

**Issue by oscarxiao** [susanBuck/e28-spring20#22]
The function *combineAmountAndName* cause the multiple replicate entry in the item[] array and only the last entry would be stored.

```js
let app = new Vue({
  el: "#app",
  data: {
    itemAmount: null,
    itemName: null,
    theItem: new Object(),
    items: []
  },
  methods: {
    combineAmountAndName: function() {
      this.theItem.amount = this.itemAmount;
      this.theItem.name = this.itemName;
      this.items.push(this.theItem);
      //return this.theItem;
    }
    // submitItem: function() {
    //   this.items.push(this.theItem);
    //   return this.items;
  }
});
```

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Shopping list</title>
    <meta charset="utf-8" />

    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js" defer></script>
    <script src="script.js" defer></script>
  </head>

  <body>
    <div id="app" v-cloak>
      Shopping list <br />
      Qty:
      <input type="text" v-model.number="itemAmount" />

      {{itemAmount}} Item:
      <input
        type="text"
        v-model="itemName"
        @keyup.enter="combineAmountAndName"
      />

      {{itemName}}

      <button @click="combineAmountAndName">Add</button>

      {{theItem}}

      <ul>
        <li v-for="item in items">{{item}}</li>
      </ul>
    </div>
  </body>
</html>
```

**Comment by angyts** [comment]
Thanks for flagging up this interesting problem. I tested it on my local. 

1) Declaring one of your data as `theItem: new Object()` is a strange way to declare a data property. I have never written as this way. How about this instead? `theItem: {}` , declaring it as an empty object.

2) There is something wrong with `this.items.push(this.theItem);`
It is definitely causing all your objects in your `items` array to be passed around `by reference`. Meaning, everything in your `items` array is referencing the same `theItem` object, instead of actually creating a new (different) object. So when `theItem` changes, all change.
How about try to create a `let itemToBeItemToTheList = {}` each time you run the function?

Seems like it works fine after that.

**Comment by oscarxiao** [comment]
> Thanks for flagging up this interesting problem. I tested it on my local.
> 
> 1. Declaring one of your data as `theItem: new Object()` is a strange way to declare a data property. I have never written as this way. How about this instead? `theItem: {}` , declaring it as an empty object.
> 2. There is something wrong with `this.items.push(this.theItem);`
>    It is definitely causing all your objects in your `items` array to be passed around `by reference`. Meaning, everything in your `items` array is referencing the same `theItem` object, instead of actually creating a new (different) object. So when `theItem` changes, all change.
>    How about try to create a `let itemToBeItemToTheList = {}` each time you run the function?
> 
> Seems like it works fine after that.

**Comment by oscarxiao** [comment]
Thank you @punggolzenith. I am still trying to understand the logic here about the *.push* function. In this function 

```javascript
combineAmountAndName: function() {
      this.theItem.amount = this.itemAmount;
      this.theItem.name = this.itemName;
      this.items.push(this.theItem);
      //return this.theItem;
    }
```
I only call it when the event listener was triggered. The *itemAmount* *ItemName* *theItem* was declared in data and initialized as Null. When function got triggered, itemAmount and itemName will be assigned to the object theItem once. Then theItem will be pushed into the last position of the items once. I kinda don't know which part went wrong.  

I also tried to declear a new object everytime when I call the function. 

```js
let app = new Vue({
  el: "#app",
  data: {
    itemAmount: null,
    itemName: null,
    theItem: {},
    items: []
  },
  methods: {
    combineAmountAndName: function() {
      let itemWillBeInItems = {};
      itemWillBeInItems.amount = this.itemAmount;
      itemWillBeInItems.name = this.itemName;
      this.items.push(itemWillBeInItems);
      //return this.theItem;
    }
    // submitItem: function() {
    //   this.items.push(this.theItem);
    //   return this.items;
  }
});
```
but Vue will say my new variable *itemWillBeInItems* is not defined on the instance.

**Comment by susanBuck** [comment]
Hi @oscarxiao - FYI I'm looking at your code now and will follow-up shortly.

**Comment by susanBuck** [comment]
@punggolzenith is correct that your `thisItem` is being passed by reference - as a result, whenever it changes, it updates any instances of it that were added to `items`.

I agree the correct approach here is to initialize a new object for every new item added. 

Below is my test/example code - note that I removed the `combineAmountAndName` method and streamlined things into the single `submitItem` method:

Example:
```js
let app = new Vue({
    el: "#app",
    data: {
        itemAmount: null,
        itemName: null,
        items: []
    },
    methods: {
        submitItem: function () {
            // Each time we submit an item, we generate a brand new object for that item
            this.items.push({
                amount: this.itemAmount,
                name: this.itemName
            });
        }
    }
});
```

I also tested the code you shared in your last thread (the code that used `itemWillBeInItems`) and that worked on my end without any errors or Vue warnings. If you're still getting an error on your end, can you push your latest changes to Github and share your repo URL? I'll clone your code and that way I can test/debug with the same exact code you're working with.

**Comment by oscarxiao** [comment]
Hi professor @susanBuck, I just git push my folder. Please let me know if you can run it. Thanks!
I also try to understand the *referencing issue*

```js
let app = new Vue({
  el: "#app",
  data: {
    itemAmount: null,
    itemName: null,
    theItem: new Object(),
    items: []
  },
  methods: {
    combineAmountAndName: function() {
      this.theItem.amount = this.itemAmount;
      this.theItem.name = this.itemName;
      this.items.push(this.theItem);
      //return this.theItem;
    }
    // submitItem: function() {
    //   this.items.push(this.theItem);
    //   return this.items;
  }
});
```
In this *combineAmountAndName* function, when I call *this.theItem*, is it refering to the *theItem in data option* ? How's theItem being pushed to all position of the array multiple time even thouge I just called the function once?

**Comment by susanBuck** [comment]
@oscarxiao I tested your code locally and was able to recreate the error:

```js
vue.js:634 [Vue warn]: Property or method "itemWillBeInItems" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
```

This error is happening because in your [index.html file on line 28](https://github.com/oscarxiao/e28/blob/master/week4/index.html#L28), you're trying to print `itemWillBeInItems` to the page:

```js
 {{itemWillBeInItems}}
```

Because `itemWillBeInItems` is just a local variable in the `combineAmountAndName` method, and not a data property of the Vue instance, it's not available to be displayed in your HTML like this. Simply remove that line and the error should go away.

**Returning back to your main question about the duplicate objects...**

To understand this, recall what I discussed earlier in the semester about Vue's [reactivity system](https://hesweb.dev/e28/notes/vue/behind-the-scenes#reactivity-system) - when data of our Vue instance is changed, those changes are propagated wherever that data is being used.

Here's a summary/breakdown of how this was working in your original code:
+ You had a data property called `theItem`.
+ You added `theItem` to your `items` array.
+ Then, you changed `theItem` - and as a result, the instance of `theItem` that was already in the `items` array changed as well. It reacted to the change.

To understand this, think about examples where we bound a `playerName` property to a text input and also printed it to the page. Anytime `playerName` was updated, it reactively changed in the input and on the page.

Same thing here with `items` and `theItem`, it's just changing within an array.

Does that make sense? Happy to clarify further/from a different perspective if needed. : )
