### ISSUE TITLE
Week 4 Quiz Question Help - v-show vs. v-if and DOM rendering

### ISSUE THREAD

**Issue by guyewhite** [susanBuck/e28-spring20#27]
Hi Team,

Having received the scores for our Week 4 assignment, here is the outcome of one of my questions below.

My first question for you: I thought v-show is processed by the DOM, but v-if is not. Did I miss-hear that? Naturally, I'm aware that A and C are rendered by the screen -- but I thought only C is processed by the DOM.

Second question: Does D really render?

<img width="798" alt="Screen Shot 2020-03-06 at 4 24 19 PM" src="https://user-images.githubusercontent.com/46040704/76132316-375a0b00-5fc7-11ea-985a-1e286b491b06.png">

**Comment by susanBuck** [comment]
`v-if` will render an element to the dom DOM *if* its value is true. 

- A _will_ be rendered because `v-if=true`
- B will _not_ be rendered because `v-if=false`
- C _will_ be rendered because v-shows always renders (and also `v-show=true`)
- D _will_ be rendered because v-shows always renders (even though `v-show=false`)

To demonstrate this, I threw the code into my Week 6 example so you can see what it looks like on the page and what the rendered DOM looks like via the web inspector. Screenshot below.

(Tip: When questions have isolated code examples like this, it can be useful to run the code and see what the results are to confirm/deny your answers. : )

![image](https://user-images.githubusercontent.com/237711/76132613-cb38d080-5fe1-11ea-9aa9-26969589d73d.png)

**Comment by guyewhite** [comment]
Thank you for the answer. I ran the code in my browser prior to submission and saw that A and C were viewable. For some reason, I thought I heard in lecture that v-if was not "processed" by the DOM so I removed A from my answer.

I think I will need to go back to Week 1 and further develop my understanding of the DOM and what its relationship is to what is viewable on screen. Those very well could be the same thing :)

Thanks for your time.

**Comment by susanBuck** [comment]
Hi @guyewhite -

> understanding of the DOM and what its relationship is to what is viewable on screen.

Just to try and help clarify this - something can be rendered to the DOM, but still not visible on the screen if CSS is hiding it.

This is the case with "D" - it's rendered to the DOM but its style is set to `display:none` so it's not visible on the screen.

If in your review you find where I may have suggested v-if isn't ever processed by the DOM - do let me know! I'm always willing to take a mea culpa if I misled (and award some points back. : )

**Comment by angyts** [comment]
Yeah this is sooo tricky!

**Comment by guyewhite** [comment]
Thanks, @susanBuck and @punggolzenith ! I appreciate the encouragement and coaching.
