### ISSUE TITLE
data property stop updating!!

### ISSUE THREAD

**Issue by oscarxiao** [susanBuck/e28-spring20#34]
Hi Everyone, my data properties stop updating. It happens sometimes. Sometimes I will change the name, it will work again. Same as my computed property, it won't show on the vue inspector. 
<img width="1859" alt="Screen Shot 2020-03-18 at 7 48 58 PM 1" src="https://user-images.githubusercontent.com/40640721/77028113-3cb73e00-6955-11ea-8cda-69d5d9184e0b.png">

**Comment by DoryAzar** [comment]
There is nothing in the code that jumps out to me. The only thing that I suspect might be happening: 
- For the data variables: they need to be used in the markup for the Vue reactivity to work. So for example, in the screen shot that you are showing, you should be able to see the reactivity when you type a firstname and lastname. But for example, if for whatever reason you are generating a random number at this state and your markup is not making use of it then it might not update in the inspector unless you hit refresh.

- computed & watch variables: this is a bit trickier because for these variables to be triggered the variable that they rely on needs to change. If for whatever reason the values of the underlying variable is not changing then neither computed nor watch would behave like you expect.

My advice is to either hit the refresh that is in the inspector or to display the variables in in HTML to see how Vue is reacting.

**Comment by susanBuck** [comment]
Hi @oscarxiao - Just an FYI that I'm going to clone your repo locally to test your code. Will post again with my findings.

**Comment by susanBuck** [comment]
Follow-up - Looks like your last commit was on March 5th. Can you update with the latest changes?

**Comment by oscarxiao** [comment]
Thank you for the info @DoryAzar. I will check again.

**Comment by oscarxiao** [comment]
Hi Professor @susanBuck, I just push them to github. As soon as I send out the email and post in the forum, the issues are automatically solved, but I didn't change anything. The new data properties come out and the computed property comes out too. I don't know why.

**Comment by susanBuck** [comment]
Thanks for updating, @oscarxiao.

Is the fix intermittent? i.e. does it still continue to fail occasionally or are you no longer able to get it to fail?

**Comment by oscarxiao** [comment]
Thanks, @susanBuck. It will happen at least once a day. It also happens when I try to update some CSS setting and the website didn't respond either. I just try to change the margin px but nothing will show up on the website. 
------------------------------------------------------------------
> Thanks for updating, @oscarxiao.
> 
> Is the fix intermittent? i.e. does it still continue to fail occasionally or are you no longer able to get it to fail?

**Comment by susanBuck** [comment]
This sounds like a browser cache issue - where the browser is caching old versions of your .js and .css files.

[Check out this thread from one of my other classes...](https://github.com/susanBuck/e15-spring20/issues/23)

It lists several strategies for how to clear your browser's cache.

Hopefully that should do the trick, but if not, let us know and we can brainstorm what else might be causing the problem. : )
