### ISSUE TITLE
Managing data between multiple Vue components

### ISSUE THREAD

**Issue by angyts** [susanBuck/e28-spring20#36]
Dear classmates, I'm trying to convert the javascript mastermind to be powered by Vue.

I'm getting stuck with Vue components.

Basically, the pin that changes colour is made up of a component such as :

```html
<!-- TEMPLATE FOR OUR COMPONENTS -->
<script type='text/x-template' id='game-pin'>
    <div class="col-3">
        <button type="button" class="btn btn-circle-large active-btn" @click="rotatePin"
                :class="button[activeColourCounter].class"
                :data-color="button[activeColourCounter].class">{{ button[activeColourCounter].name }}
        </button>
    </div>
</script>
```

```js
// Sets the number and type of buttons, go to CSS to select color
const button = [
    {class: 'g', name: 'Green'},
    {class: 'r', name: 'Red'},
    {class: 'y', name: 'Yellow'},
    {class: 'b', name: 'Blue'},
    {class: 'o', name: 'Orange'},
    {class: 'p', name: 'Purple'}
];

Vue.component('game-pin', {
    data: function () {
        return {
            button: eval(button), // get the global object
            activeColourCounter: 0,
        }
    },
    template: '#game-pin',
    methods: {
        rotatePin: function () {
            this.activeColourCounter = (this.activeColourCounter + 1) % 6; // So that it will never go out of the list
        }
    }
});

```

In each game round, a row of pins can be changed and when the round ends, the user input will be checked against the computer's hidden answer.

The trouble is this Vue component `game-pin` is a child of another component `game-row` which is a child of the main Vue instance. I need a way to get the `state` of the colour of the pins that the user selected.

The complexity adds on because after each round, the old pins are supposed to stay there and not become reactive anymore, while the `active-row` moves to the next one...

I'm out of my wits... If i run out of time... I might end up just copying my old native JS code hahaha...

**Comment by DoryAzar** [comment]
Hmmm... I am guessing that the state of the user-selected colors is somewhere in your main Vue. Have you considered passing that state as a prop to your components?

**Comment by vthil3049** [comment]
Interesting... just wondering if you can emit a custom event from your rotatePin() method of game-pin, which can be captured by game-row.
https://forum.vuejs.org/t/passing-data-back-to-parent/1201/2

**Comment by angyts** [comment]
> Interesting... just wondering if you can emit a custom event from your rotatePin() method of game-pin, which can be captured by game-row.
> https://forum.vuejs.org/t/passing-data-back-to-parent/1201/2

Thanks @vthil3049 , from the post I also found this:

```html
<div v-for="(element, index) in myArray">
  <child @clicked="onClickChild(index, ...arguments)"></child>
</div>
```

Seems like what I need. 

I also figured I can set a `isActiveRow` data prop, and set all the events to trigger only if this the row `isActiveRow`, great! Thanks, I will go try implement it later.

**Comment by susanBuck** [comment]
This question delves into the realms of **state management** - with state being the **data of our applications**.

With a simple parent instance to single child relationship, state management is straightforward enough - pass data from the parent to child via **props**, and data from the child to parent via **events**.

When we start talking about nested children, though, it becomes more complex because we need to start flowing data from _parent > child a > child b_, etc. 

This is possible via events/props, it can just get a little messy as the complexity of the application and components grow.

Later in the semester - we'll address this and talk about different approaches to state management. This will include a discussion of a [simple design pattern for state management](https://vuejs.org/v2/guide/state-management.html#Simple-State-Management-from-Scratch) to more robust options such as [Vuex](https://vuex.vuejs.org/), a state management library for Vue.js.

In the meantime, for Project 1, I recommend sticking to events/props to pass your data between parent/child instances, even if it means passing data from _parent > child a > child b_. It'll be good practice for working with events/props, and I think It'll really help you understand/appreciate state management when we get to it. 

Follow-up if you have any difficulties in your code when implementing the above student suggestions. : )

**Comment by angyts** [comment]
By the way an update, since we haven't learnt `Vuex` yet, I had to use a rather hacky way to manage this. Seems a little anti-Vue when I do this...

There is this thing called `$refs` from the [Vue documentation](https://vuejs.org/v2/api/#ref).

```html
<game-row v-for="(round, index) in rounds" :key='index' ref="index" :class="{ 'inactive-row': !round.isActive }" :is-old-row="rounds[index].isOldRow" :check-answer="recordOfAllAnswers.filter(answer => answer.id == index)"></game-row>
```

After you label a component with the `ref`. You can reference it as a global variable.

```js
let answer = [...this.$refs.index[this.roundsLeft].userAnswer];
```
