### ISSUE TITLE
Calling a method of a class instance of vue data element.

### ISSUE THREAD

**Issue by procchio77** [susanBuck/e28-spring20#38]
I converted the core logic of my game to a javascript class with the idea of having that class be reactive when I bind an instance of it to the vue data property.

like so
```js
let currentGame = new TicTacToe();
let app = new Vue({
    el: '#app',
    data: currentGame
})
```

It seems to work, as I am able to build the tictactoe cells.  However, I get an error when I try to call a method on that class using v-on:click.  

> Property or method "currentGame" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property

Is what I am doing even possible?

Here is the html
```html
    <div id='app' v-cloak>
        <div class="tic-tac-toe" id="board">
            <div v-for='(cell, i) in cells' v-on:click='currentGame.turn(i)' class="cell">
            </div>
        </div>
    </div>
```

```js
class TicTacToe {

    constructor() {
        this.player1 = 'X';
        this.player2 = 'O';
        this.isEndGame = false;
        this.gamesToPlay = 0;
        this.gamesPlayed = 0;
        this.whoToBegin = null;
        this.winner = null;
        this.currentTurn = this.player1; //initial player
        this.turnCounter = 0;
        this.cells = new Array(9).fill().map(c => new cell());
    }

    turn(i) {
      // logic
    }

    checkWinner() {
       //logic
        }

}
```

**Comment by ambielecki** [comment]
So, I definitely wouldn't recommend doing it this way, but I was able to make something similar work by using `v-on:click='$data.turn(i)'`. currentGame isn't a property of vue's data, the whole new object is.  

But it doesn't feel like the Vue way to do things, probably better off sticking to just data properties and methods. (But my curiosity got the better of me and I had to see if it would work :) )

**Comment by susanBuck** [comment]
What is the purpose of encapsulating the game in its own class?

You noted it was because you wanted it to be reactive - but if you encode the game as data properties and methods of the root vue instance (as @ambielecki suggested) it will be reactive. I don't think it's necessary to add another layer of a class in this scenario.

The only argument I could see for it would be if you were looking for modularity/reusability (e.g. you want to be able to use the game in other places) - but if that's the case, then it should be a Vue component.

**Comment by procchio77** [comment]
Thanks.  

I went down this road because I was thinking of separation of concerns. Doing it this way would make it easier to swap front-end frameworks in the future, if the need ever arises.

**Comment by susanBuck** [comment]
@procchio77 - Gotcha, that makes sense. You're thinkinging bigger picture and separating business logic - I get that. : ) 

You might find this article interesting:
http://vuejs-course.com/blog/separating-ui-and-business-logic-in-vue-components

**Comment by procchio77** [comment]
So i resorted to using vue data and properties, but I hit the following issue. I am sure the answer is staring me in the face, but I wrote so much code at work today that I am coded out.  

I have a cells object like so
```
cells: [
            { text: null, highlighted: false },
            { text: null, highlighted: false },
            { text: null, highlighted: false },
            { text: null, highlighted: false },
            { text: null, highlighted: false },
            { text: null, highlighted: false },
            { text: null, highlighted: false },
            { text: null, highlighted: false },
            { text: null, highlighted: false },
        ]
```
I keep getting keep cannot read property **text** of undefined in my nextTurn method call
I should add that when I click a 2nd time in the cell the text value does get set.

Any ideas what I missing?

Method Code
```
methods: {

        nextTurn: function (i) {
            console.log(this.cells[i].text); //throws error
            if (!this.isEndGame && !this.cells[i].text) {

                this.cells[i].text = this.currentTurn;
                this.turnCounter++;

                if (this.turnCounter > 4) {
                    this.checkWinner();
                }

                this.currentTurn = (this.currentTurn === this.player1) ? this.player2 : this.player1;

                //computer player
                this.nextTurn(this.pickCell());
            }
        },
```
Html code
```
<div class="tic-tac-toe" id="board">
            <div v-for='(cell, i) in cells' v-on:click='nextTurn(i)' v-bind:class='{highlightWinner: cell.highlighted}'
                class="cell">
                {{cell.text}}
            </div>
        </div>
```

**Comment by susanBuck** [comment]
@procchio77 - I cloned your code locally to test and got the following error at (seemingly) random:

```
[Vue warn]: Error in v-on handler: "TypeError: Cannot set property 'text' of undefined"
```

I think I tracked it down to a issue in `nextTurn` when the computer's move is chosen, specifically this line:

```js
let randomCell = this.cellsToPlay[Math.floor(Math.random() * this.cellsToPlay.length)];
```

Here you generate a random number to extract a value out of `cellsToPlay`.

At the start of the game, cellsToPlay contains only numerical values:

![image](https://user-images.githubusercontent.com/237711/77775142-86bdb500-7022-11ea-8ec6-2c6b551e7c09.png)

However, as the game is played, cellsToPlay is updated to track which character (`X`,`O`) is played in which cell. For example:

![image](https://user-images.githubusercontent.com/237711/77775207-9e953900-7022-11ea-8170-07279acb2792.png)

The problem occurs when the random number that is generated is the same number for an already played spot. For example, imagine the random number generated was `5`... Rather than returning the cell `5` to play, it would now return `X`:

![image](https://user-images.githubusercontent.com/237711/77775496-fe8bdf80-7022-11ea-8f2b-d7e4ea62b486.png)

And that's when the error gets triggered, because down in `turn` it would effectively be trying to do this:

```js
this.cellsToPlay['X'] = this.currentTurn;
```

and `this.cellsToPlay['X']` is undefined.

To fix, you'll want to add some logic to prevent it from picking cells that have already been picked.

Let me know if you have any follow-up questions about this!
