### ISSUE TITLE
Real world design of a Vue application

### ISSUE THREAD

**Issue by angyts** [susanBuck/e28-spring20#49]
Thank you professor @susanBuck for bringing us to this point. This Vue framework is indeed quite powerful and flexible.

So far we are transiting in the course from learning the basic tools to making full stack applications with Vue.

Something I feel that I have not learnt, or perhaps will be covered later will be the **"design process"** of designing a Vue application.

For example previously we would build websites based on "functions" or "pages". Like this page does this, it would "inherit" some base templates and navigation then go into the specific parts of the page. So we start building from the big framework, then the smaller things.

**In Vue**, however, the paradigm seems to be a little different: seems like we are starting from building the **smallest** component then building it up. Then choosing the components to display based on the "page"/routing.

Can you please share with us, in a real world project, what is the usual paradigm or design process that is taken? Also how does it work when there are different people working on the team?

**Comment by susanBuck** [comment]
Hi @punggolzenith -

I think you'll find this resource to be helpful: 

https://github.com/gothinkster/vue-realworld-example-app

It's the code base for an example social blogging application called Conduit.

Demo here: https://vue-vuex-realworld.netlify.com/#/

Functionality includes:
+ Authenticate users via JWT (JSON Web Tokens)
+ Create, read, and update users
+ Create, read, update, and delete articles
+ Create, read, and delete comments
+ Display paginated lists of articles
+ Favorite articles
+ Follow other users

Regarding this question:
> Also how does it work when there are different people working on the team?

This is a big question. : )

I think one of the biggest variables here is just size/scope of the project and team.

Obviously a large project with a big team is going to require a clear infrastructure that guides development from design to execution. There will be many stakeholders - from project managers, designers, coders, quality assurance testers, etc.

A smaller project with a smaller team might have less division, with each individual handling multiple roles instead of one specific role.

At the very least, whenever we're talking about collaboration on a code-based project, a key requirement is having a version control system (like Git) in place to track changes, keep code bases in sync, manage merge conflicts, etc.

Adding on to that, it's important that the team have a clear and agreed upon workflow that they follow when using VC. Here's a good article on several workflows: https://www.atlassian.com/git/tutorials/comparing-workflows

I hope the above information is helpful and addresses your questions. If I missed anything (or misinterpreted your questions), let me know!
