### ISSUE TITLE
Zipfoods -  Not able to load images - single vs. double quotes

### ISSUE THREAD

**Issue by maqboolk** [susanBuck/e28-spring20#51]
Zipfoods.

Every time I paste and save following template, all single quotes are converted to double quotes, and after fixing the path to image with single quotes image don't want to load.

Original template:

```html
<template>
    <div class='product'>
        <div class='product-name'>{{ product.name }}</div>
        <img class='product-thumb' :src='"./../assets/images/products/" + product.id + ".jpg"' />
        <p class='product-description'>{{ product.description }}</p>
        <div class='product-price'>${{ product.price }}</div>
    </div>
</template>
```

After paste and save, it converts to double quotes in VS code

```html
<template>
  <div class="product">
    <div class="product-name">{{ product.name }}</div>
    <img class="product-thumb" :src=""./../assets/images/products/" + product.id + ".jpg"" />
    <p class="product-description">{{ product.description }}</p>
    <div class="product-price">${{ product.price }}</div>
  </div>
</template>
```

i tried fixing the path with single quotes inside double quotes but i am not able to see any images.

**Comment by susanBuck** [comment]
First, I'll note that you can configure the Vetur plugin we're using to specify whether you prefer single or double quotes.

For example, in my VSCode `settings.json` file, I have the following config, setting single quotes as my preferred quote:

```
"vetur.format.defaultFormatterOptions": {
        "prettier": {
            "singleQuote": true
        },
        "prettyhtml": {
            "singleQuote": true
        }
    },
```

One way to address the problem you're having is to implement that above setting so that you can surround your attribute values in single quotes like so:

```html
<img class='product-thumb' :src='"./../assets/images/products/" + product.id + ".jpg"' />
```

In the above example, the  value for the `src` attribute is surrounded by single quotes (while the strings within it are surrounded by double quotes).

That should load the image, rendering something like this in the DOM:

```html
<img data-v-1acef832="" src="/img/1.418d31d2.jpg" class="product-thumb">
```

Note how the src is set to `/img/1.418d31d2.jpg`, which is a compiled version of that image created by webpack.

Now, let's say you prefer to use double quotes as your primary quote instead of single quotes...

```html
<img class="product-thumb" :src="'./../assets/images/products/' + product.id + '.jpg'" />
```

In this example, we use double quotes to surround the value for the `src` attribute (and the strings within are surrounded by single quotes). That will be rendered in the DOM like this:

```html
<img data-v-1acef832="" src="./../assets/images/products/1.jpg" class="product-thumb">
```

Note the image src is set to `./../assets/images/products/1.jpg` - This path shows that webpack never compiled this image for us - and it obviously won't work in the browser, because the assets directory is in our `src` directory, and not something the browser has access to.

To address this, you can set your image src using a `require` method, which will force it to resolve the correct path:

```html
<img
    class="product-thumb"
    :src="require('./../assets/images/products/' + product.id + '.jpg')"
/>
```

This will correctly render in the DOM using the compiled image path:

```html
<img data-v-1acef832="" src="/img/1.418d31d2.jpg" class="product-thumb">
```

To learn more about this, check out the docs on [*vue-loader* and asset handling](https://vue-loader.vuejs.org/guide/asset-url.html#asset-url-handling) (*vue-loader* is the webpack plugin that Vue CLI uses to compile our Single File Components).

**Comment by maqboolk** [comment]
Thank you very much @susanBuck. 
I configured the vetur plugin in settings and it worked.

**Comment by susanBuck** [comment]
Glad that worked! And apologies for not actually mentioning this sooner - because my Vetur is configured to use single quotes, I always forget it's an issue for students using double quotes. : )
