### ISSUE TITLE
CLI sudo installation with errors showing up!

### ISSUE THREAD

**Issue by oscarxiao** [susanBuck/e28-spring20#53]
I was trying to install CLI in my terminal by running 
```
$sudo npm install -g @vue/cli
```
And these errors shows up. 
<img width="1412" alt="Screen Shot 2020-04-09 at 2 54 08 PM" src="https://user-images.githubusercontent.com/40640721/78944132-15462380-7a72-11ea-91e2-db379232478a.png">
<img width="833" alt="Screen Shot 2020-04-09 at 2 54 37 PM" src="https://user-images.githubusercontent.com/40640721/78944145-18411400-7a72-11ea-844d-540375af1a4f.png">
*Are these error msg normal?*

**Comment by DoryAzar** [comment]
Somebody else had the same issue. You need to upgrade node. It seems you are using v 12.X. The latest is 13.X.
here is the thread: https://github.com/susanBuck/e28-spring20/issues/46

**Comment by oscarxiao** [comment]
Hi @DoryAzar ,How should I properly upgrade the node version? 
Can I use this? 

```
sudo npm install npm@latest -g
```

**Comment by DoryAzar** [comment]
It depends on how you installed the first time. I would say start from a clean state and use the node package installer from the site. It’s also described in the notes. That would take care of it for you.

**Comment by oscarxiao** [comment]
@DoryAzar, I used the [link]( https://nodejs.org/en/download) provided in the note to install npm package. 12.16.2 is the latest version they provided. How should I get 13.X?

**Comment by DoryAzar** [comment]
I went for the « Current » not the LTS.
The current is 13.X

**Comment by susanBuck** [comment]
I think the LTS version `12.16.12` should be sufficient (for reference, I just checked my own version and I'm on `12.16.1`). Also your `node-gyp` is up to date at `5.1.0`.

Doing some research now into the issue. Will follow up again when I have more information.

**Comment by susanBuck** [comment]
Try running:
```
$ sudo npm cache clear --force
```

Ref: https://github.com/vuejs/vue-cli/issues/1809

**Comment by susanBuck** [comment]
The Vue CLI docs suggest that installing via `sudo` might introduce some issues: 
https://cli.vuejs.org/guide/troubleshooting.html#running-installation-with-sudo-or-as-root

Given this, I'd like to have you re-install @vue/cli, this time without `sudo`.

To do this, first uninstall:

```bash
$ npm uninstall -g @vue/cli
```

(If that fails due to permission issues, prefix with `sudo` and run again).

Once it's uninstalled, run the following command just to make sure you have the correct permissions on your `node_modules` directory:

```bash
$ sudo chown -R $USER /usr/local/lib/node_modules
```

Finally, reinstall @vue/cli, *without* sudo:

```bash
$ npm install -g @vue/cli
```

When/if that fails, share the full error output with us (please share the text instead of a screenshot - it makes it easier to copy/paste from the error for research purposes. : )

**Comment by susanBuck** [comment]
@oscarxiao Checking in to see if there is still a pending issue here/anything I can help with. If not, we can close this thread. : )
