### ISSUE TITLE
Image storage

### ISSUE THREAD

**Issue by maqboolk** [susanBuck/e28-spring20#59]
Image storage in cloud and loading images from cloud will be covered in future lectures?

**Comment by susanBuck** [comment]
It's not on the schedule, no. Kind of a broad topic, not necessarily specific to Vue.

But if you elaborate a bit more on what you're trying to accomplish (e.g. which cloud storage platform are you interested in working with, are you looking for users to be able to upload images, etc.) I can provides some guidance/point you in the right direction.

**Comment by maqboolk** [comment]
@susanBuck ,

Right now when we create a new product in zipfoods, we are not uploading an image, But in future if we want to upload an image, where do we store and how can we upload / download ? do we use api for it?

**Comment by ambielecki** [comment]
In general this is still something I would handle with the same backend that is serving my more traditional JSON API responses, but it really is very dependent on what technologies you want to use. You can still push images with something like axios, you'll just be changing the content type from something like application/json to multipart/form data and sending a Formdata object instead of a json package.

For a simple prototype I generally just store files on the same web server where my backend API sits (so on the disk of a DIgital Ocean droplet for example). You would then need code to serve the image. You'll need some other storage solution if you're dealing with any type of volume (like an S3).  In general, I'd still let the backend API handle moving files to S3 (so SPA -> backend -> S3), along with validating the files.

I've definitely found file handling to be one of the thornier issues with an API driven frontend.

**Comment by maqboolk** [comment]
@ambielecki  . Thank you. Sounds complicated.
