### ISSUE TITLE
Creating a "google calendar canvas"

### ISSUE THREAD

**Issue by angyts** [susanBuck/e28-spring20#65]
Dear wonderful classmates,

I'm trying to do some type of scheduling app. Only then I realized the complexity and intricacies of this wonderful google calendar application that we take for granted.

I'm a little stuck trying to get time slots to display like in google calendar.

Say I have a time slot: 8am to 9am.

How can I use some Vue magic or javascript magic to display it on the browser?
Some ideas:

- Should I fill up the canvas with a `15minuteTimeSlot' component? Then use that to slowly build the whole thing up? And change its class based on whether the time slot is filled? Problem is what if there are more than one appointment on that time slot?

- Another way would be to dynamically create a `newAppointment` component when an appointment is booked, but how do i "magically" display it in the right start time and end time?? 

- Another way would be to use external libraries like D3, to actually `draw` out whatever I want to render.

Any ideas would be appreciated! Or telling me to give up and change project might work too...

**Comment by DoryAzar** [comment]
Hmmm, since this project is more about Vue Single File Components and server interactions from Vue, I would suggest that you look at open source libraries with a Calendar or Gantt components. Otherwise, you are going to spend a lot of time trying to visualize time events as opposed to focusing on what the course is about. 

There are plenty of Vue libraries that you can use that could give you that.
You can check: https://github.com/neuronetio/gantt-elastic
or Vuetify: https://vuetifyjs.com/en/components/calendars/

Or there are also plenty of CSS, javascript or Bootstrap libraries for Calendar or Gantts. You could better use your time to turn them into Vue components.

Just my 2 cents.

**Comment by angyts** [comment]
@DoryAzar Oh wow, I didn't know there are such powerful libraries like vuetify, thanks! I'm going to try it now.

**Comment by angyts** [comment]
Oh some more to update, if you are adding vuetify from the Vue-Cli, make sure you add it right at the **START**.

It totally replaced my app.vue file... Luckily i just made a commit... i could rollback...

**Comment by angyts** [comment]
OMG! I'm almost going to finish, this feels too easy like i'm cheating.

**Comment by DoryAzar** [comment]
Make sure you have components of your own creation to respect the minimum requirements of the project. Remember you need it to be SPA, at least one SFC of your own creation ideally and server interactions.
