### ISSUE TITLE
DRM / Code Protection

### ISSUE THREAD

**Issue by guyewhite** [susanBuck/e28-spring20#7]
Hi Team,

I may be getting way ahead of myself here: Since my goal is to create a give-away product to be immediately implemented for my clients, is there a way to protect from potential thieves from stealing the underlying script.js file? 

For example, one of my products is a personality-quiz-like assessment. It’s perfectly fine that anyone on the planet takes the personality quiz and sees their results (I don’t want to hide it behind a pay wall). However, the underlying code of HOW my algorithm arrives at their final score is confidential and proprietary to me.

An hour of googling is leaving me with mixed messages.

Any ideas about how I can handle this?

**Comment by angyts** [comment]
Your `script.js` will be publicly available unless it is:

1) Behind a login wall.

Your `algorithm logic.whatever file` will be publicly available unless it is rendered behind a server, meaning:

1) You will obtain the `input` from your user from a `form`. Then calculate with your secret sauce on your server, then return a new html page/address.  OR

2) You will create a server side API to receive data from your client side, calculate with your secret sauce on the server, then return a JSON HTTP response to your client side. And on your client side you might have to use `Vue.js` with `Vue-Axios` or plain JS `XMLHttpRequest`, to send the data and parse the JSON return.

There are always creative ways to deal with things such as:
1) Write such a spaghetti code in your algorithm in your `scripts.js` so that even if a coder bothers to read it, he can't be bothered to understand it.
2) Write your name everywhere hidden in the script or even make a graphic with the code with your name. Then let them steal it then contact a lawyer to deal with them.
3) Compile the code in C or some other language that can be complied, then have your JS call it, but as far as I know that can only be done on server side.

**Comment by ambielecki** [comment]
Yeah, the only real way to keep you logic fully protected and secret is to run it server-side in response to API calls from your front-end code.

You can do things such as minify / uglify your js (using a package such as <https://www.npmjs.com/package/uglify-js>), which will make it much more difficult for a human to parse and understand, but in the end, all of the correct logic is still there (especially if you are doing things like setting arrays / objects of scores and such for matching answers to their value, that stuff is harder to hide).

**Comment by susanBuck** [comment]
I agree with @punggolzenith and @ambielecki's answers. 👍

+ The most secure way to make the algorithm hidden is to **offload it to the server**.
+ Anything done in the browser is accessible to the end user. You can make it harder to read, but you can't completely obscure it.

**Comment by guyewhite** [comment]
Thanks, @susanBuck, @punggolzenith, and @ambielecki!
