### ISSUE TITLE
Fixing ShowFeatured.vue

### ISSUE THREAD

**Issue by procchio77** [susanBuck/e28-spring20#71]
I went to go fix the ShowFeatued.vue component to use an api call. Took a similar approach to #60, but the filter callback does not seem to be wired correctly.  product is undefined in the isMatch method.

```js
 methods: {
        isMatch: function(product) {
            console.log(product); //throws undefined
            return product.categories.includes(this.category);
        }
    },
    mounted: function() {
        app.api.all('products').then(response => {
            this.products = response;
             this.featuredProducts = this.products.filter(this.isMatch(),this.category);
        });
    }
```
Any ideas why?

**Comment by maqboolk** [comment]
try isMatch without parentheses **()**

I am just guessing. i might be wrong

**Comment by guyewhite** [comment]
@procchio77 , One thing I notice about the SFCs using the API is that the methods are not inside the SFC itself, but in the pages that call them. For example, in my setup for ShowFeatured in Zipfoods, the API call itself happens on the home page. It then passes it as a prop to the show featured SFC.

Secondarily, I found that I had two options when it came to filtering:

1. Write an API function to accomplish this, as @susanBuck suggests [here](https://github.com/susanBuck/e28-spring20/issues/58).

2. Create a copy of the initial data pulled from the database and then do filtering on what was pulled down.

Hope this helps in a small way.

**Comment by procchio77** [comment]
@maqboolk That didn't work.

@guyewhite Yes, I was going to look into applying the filter with the api call. Your post is helpful.

My guess is that the filter method wasn't working because the response data being returned from the api is an object, and the filter method only works for an Array.  I haven't had time to check yet, but will do so once my workday is over.

**Comment by procchio77** [comment]
@maqboolk @guyewhite @susanBuck 

For those that are interested, this is how I fixed the ShowFeatured page using one api call.

I modified the filter method Susan posted in #58 to 

```js
 async filter(collection, field, operator, value) {
        try {
            const querySnapshot = await this.api.collection(collection).where(field, operator, value).get();
            let results = {};

            querySnapshot.forEach(doc => {
                results[doc.id] = doc.data();
            });

            return results;
        }
        catch (error) {
            return 'Error getting documents: ' + error;
        }
    }
```
then here is the mounted function in ShowFeatured.vue that sends the filter looking for categories that have 'snacks'

```js
 mounted: function() {
        app.api.filter('products', 'categories', 'array-contains', 'snacks').then(response => {
        this.featuredProducts = response;
    });

    },
```
Don't forget to replace 'snacks' with the prop (this.category)
Feel free to share if anyone knows of a cleaner way :)

**Comment by guyewhite** [comment]
@procchio77 thanks for sharing. @susanBuck introduced me to Lodash earlier this week, which I'm now in love with: [https://lodash.com/docs/4.17.15#filter](https://lodash.com/docs/4.17.15#filter)

**Comment by procchio77** [comment]
@guyewhite Thansks!

I am trying to refrain from using more helper libraries.  I am at a novice level with Javascript, been a server-side developer; so I am trying to force myself to do all of this as purely as I can :)

Once I am comfortable with filtering with objects and arrays and casting from one to the other in javascript, I will definitely leverage lodash.

**Comment by susanBuck** [comment]
@procchio77 Your solution looks good. 👍

Jumping back to your original code, I was curious why invoking `isMatch` as a component method was not working.

To test, I set up my `ShowFeatured.vue` component with this code:

```js
methods: {
        isMatch: function(product) {
            console.log(product); // Yields: Product data
            console.log(this); // Yields: VueComponent
            return product.categories.includes(this);
        }
    },
    computed: {
        featuredProducts: function() {
            return this.products.filter(this.isMatch, this.category);
        }
    }
```

In my case, I was able to access `product` within the `isMatch` component method. The problem, however, was that `this` in that context was the actual VueComponent, not the given snack.

Given this, I would not recommend setting up your filtering callback function as a Component method.

Probably the most straightforward approach is to use an arrow function:

```js
computed: {
        featuredProducts: function() {
            return this.products.filter(product =>
                product.categories.includes(this.category)
            );
        }
    }
```

Of course this is a moot point since you're now getting your data from the API, but just wanted to include this info here for hindsight.  : )

Going to go ahead and close out this thread, but feel free to keep the discussion going or start a new thread if you have additional questions.

**Comment by procchio77** [comment]
@susanBuck I did not even try computed because of the lifecycle issue that was mentioned in post #60  Did you not have that issue?

**Comment by susanBuck** [comment]
Hi @procchio77 - 

Apologies - I read your first post too fast. : ) I was focussing in on the issue that the filter callback was not working as expected, and I thought it was just something related to the callback being a component method. When I was running my tests, I was still working with my version of `ShowFeatured.vue` that was pulling from `products.js` instead of the API, which of course did not present any problems with needing to wait for products data to be loaded.

Now that I'm in sync, I agree with your assessment:

> My guess is that the filter method wasn't working because the response data being returned from the api is an object, and the filter method only works for an Array.

Here's how I would re-write things to work with the object:

```js
export default {
    name: '',
    props: ['category'],
    data: function() {
        return {
            products: null,
            featuredProducts: []
        };
    },
    methods: {
        loadFeaturedProducts: function() {
            // Iterate through all our products
            Object.keys(this.products).map(key => {
                // If this product includes the category we're filtering for...
                if (this.products[key].categories && this.products[key].categories.includes(this.category)) {
                    // Add it to our featuredProducts array
                    this.featuredProducts.push(this.products[key]);
                }
            });
        }
    },
    mounted: function() {
        app.api.all('products').then(response => {
            this.products = response;

            // Load featured products now that we know we have product data
            this.loadFeaturedProducts();
        });
    }
};
```

Or, your solution of doing the filter as part of the API call is good too. 👍

(All that being said, stay tuned for this week when we get into state management - this will allow us to share product information amongst components easily so we don't have to keep making repeat/similar API calls for the same data)

**Comment by susanBuck** [comment]
Note: I updated my above code so the if statement checks that a product has categories:

```js
if (this.products[key].categories && this.products[key].categories.includes(this.category)) {
```

Without that, if you add a new product (which will not have categories associated with it), you'll run into errors.
