### ISSUE TITLE
Do i need to execute 'npm install --production' ?

### ISSUE THREAD

**Issue by maqboolk** [susanBuck/e28-spring20#76]
@susanBuck 

Do i need to execute "npm install --production" command every time i pull changes to production server?

Yesterday after pulling my changes I didn't execute the command, but my app worked fine.

I pulled first time yesterday after i set up the domain for p2 couple weeks ago. At that time i executed 'npm install --production'

**Comment by susanBuck** [comment]
Hi @maqboolk - Because we're building our projects locally and deploying the compiled `dist` folder, it's not necessary you run `npm install --production` on production every time (or even at all).

*If* you were building on production (following [option B shown here](https://hesweb.dev/e28/notes/vue/build-comprehensive#building-for-production)) then you would want to run `npm install --production` on production so the project could be built using up-to-date dependencies.

Or, if you had some npm dependencies you wanted to utilize on the server that weren't specific to your build (maybe some command line scripts?), that would be another reason to run `npm install --production`, as it would make that `node_modules` directory available there.

**Comment by susanBuck** [comment]
Follow up: I realize my notes are misleading in they do say to run `npm install --production`: https://hesweb.dev/e28/notes/vue/build-comprehensive#deploying-on-production

In past semesters, I did have us build on the server so that was step is necessary. Now that we're building locally, I need to update those instructions. Sorry for any confusion. : )

**Comment by maqboolk** [comment]
@susanBuck Thank you.
