### ISSUE TITLE
2 issues with Bootstrap Vue and updating with Firebase

### ISSUE THREAD

**Issue by tmussa1** [susanBuck/e28-spring20#79]
I have two issues

1) My datepicker is not rendering properly. I am using the BootStrap Vue library
2) I am trying to have an updating functionality but searching with an attribute other than ref. If you can please share a template of how to do that. Here is what I got thus far https://github.com/tmussa1/p2/blob/master/public/callFirebase.js

Here is my repo

**Comment by susanBuck** [comment]
Hi @tmussa1 -


**Re: 1**
Are you referring to the numbers being aligned in correctly? Just want to make sure we're talking about the same problem before I start debugging.

![image](https://user-images.githubusercontent.com/237711/80323387-0ba21700-87f9-11ea-8122-2a6ceebc2fb1.png)


**Re: 2:**
Do the filter techniques described in [this thread](https://github.com/susanBuck/e28-spring20/issues/58) fit the bill for what you're trying to accomplish?

**Comment by tmussa1** [comment]
Hello Professor,

Yes the problem is the numbers not alligining correctly.

As for the second problem, I want to some how obtain the ref based on the
name and then do an update.

Regards,
Tofik Mussa

**Comment by susanBuck** [comment]
Re 1)

You're importing this CSS for Bootstrap Vue:

**Comment by susanBuck** [comment]
You're importing this CSS for Bootstrap Vue:

```js
import 'bootstrap/dist/css/bootstrap.min.css';
```

If I switched it to the two css files [they list in the docs...](https://bootstrap-vue.org/docs/)

```js
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'
```

Then it works as expected:

![image](https://user-images.githubusercontent.com/237711/80323637-a4856200-87fa-11ea-8f66-a5ced057ca35.png)

I'll reply again with more details on obtaining ref based on name.

**Comment by tmussa1** [comment]
Hello Professor,

Thank you so much. That helped fix the datepicker issue.

When I said name, it is name of the player in my case. I know it is not a
requirement, but I also want to know how update works after obtaining the
ref.

Regards,
Tofik Mussa

**Comment by susanBuck** [comment]
>  I want to some how obtain the ref based on the name and then do an update.

In the [thread I referenced above](https://github.com/susanBuck/e28-spring20/issues/58), I offered a filter method you can add to `api.js`:


```js
/**
 * 
 */
async filter(collection, field, operator, value) {
    try {
        const querySnapshot = await this.api.collection(collection).where(field, operator, value).get();
        return querySnapshot.docs;
    }
    catch (error) {
        return 'Error getting documents: ' + error;
    }
}
```

Using this, you could query for the document based on any field - in your case, name.

From the document(s) you get in return, you could access the ref id.

As for doing the update, this is not something I had added to the `api.js` file I shared, but you could add it...

[Here's the Firestore API docs for their update method...](https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentReference#update)

Using that info, here's an `update` method we can add to `api.js`:

```js
/**
 * Update a document from a collection by id
 */
update(collection, id, newValues) {
    this.api
        .collection(collection)
        .doc(id)
        .update(newValues);
}
```

Then here's an example using both the `filter` and `update` methods, which I use to get the product with the slug `gold-medal-flour` and update the price to $3:

```js
app.api
    .filter('products', 'slug', '==', 'gold-medal-flour')
    .then(response => {
        // This assumes your filter will only yield 1 result
        let docRec = response.shift();
        app.api.update('products', docRec.id, {
            price: 3.0
        });
    });
```

Let me know if you have questions about the above code.

**Comment by tmussa1** [comment]
Hello Professor,

Thank you so much. That was really helpful. I have been struggling to find
out where I am treating a number as a string. My loss count doesn't update
and returns "NaN". I have tried parsing to integer in every calling method.
https://github.com/tmussa1/p2/blob/master/public/callFirebase.js Maybe you
can help me with a second eye.

Regards,
Tofik Mussa

**Comment by susanBuck** [comment]
Hi @tmussa1  - Sure - taking a look now. Will follow-up with what I find out.

**Comment by susanBuck** [comment]
I took a closer look at your code and identified a few places that I believe are the source of your problem.


## Problem 1) playerName is not being persisted after a page refresh

Example:

I go to /

I enter player name `susan`, hit submit.

I arrive at /categories (HomePage.vue) and confirm that `playerName` in this component is registered as `susan`

I go to my code editor to make some change, maybe adding a console.log, when I return to the browser, hot module reloading has forced the browser to refresh and now `playerName` is empty.

Any future operations (updating win/loss counts, etc) will now not work as expected because no playerName is available.

To address, I suggest storing/retrieving the playerName from local storage, similar to how I did with cartCount in last week's lectures.




## Problem 2) Repeat users with the same name are being stored

Every time I start the game over, if I use the same name (e.g. `susan`) it creates new collections using that same name, instead of updating the existing collection of that same name.

As a result, when you try to filter and retrieve the win/loss count by the playerName, you may be getting a record you're not expecting. 

One way to address this would be if a player enters a name that already exists, skip the step of creating a new collection with that name.


## Problem 3) Stats.vue is setting a NaN loss count

To reproduce: I delete all collections via the Firebase console to avoid Problem 2 described above.

I go to the homepage, enter player name `susan`, choose "Chicken", enter three wrong answers to trigger a loss and the incrementing of the loss count.

I confirm via the console all the data looks good:
![image](https://user-images.githubusercontent.com/237711/80412203-7f94fb80-889b-11ea-8348-05565ed382e2.png)

Next, I navigate to Scores, and just this action of loading that component updates my `losses` to be `NaN`:

![image](https://user-images.githubusercontent.com/237711/80412278-a0f5e780-889b-11ea-865f-99f36c94fc3c.png)

This happens because in Stats.vue you invoke `getLossCount` as a synchronous function and expect a return value:

![image](https://user-images.githubusercontent.com/237711/80412875-853f1100-889c-11ea-9bac-8ca2a82fcd47.png)

To understand why you can't do this, let's look closer at the function:
```js
export function getLossCount(playerName) {
    if (!firebase.apps.length) {
        firebase.initializeApp(config);
    }

    let api = firebase.firestore();

    filter('users', 'name', playerName).then(function (result) {
        let docRef = result.shift();
        api
            .collection('users')
            .doc(docRef.id)
            .get()
            .then(function (doc) {
                console.log('losses ', doc.data());
                return parseInt(doc.data().losses); // <-- RETURN 1, FROM WITHIN FILTER'S THEN
            })
            .catch(function (error) {
                console.log('Error getting documents: ' + error);
            });
        return result.shift(); // <-- RETURN 2, FROM WITHIN FILTER
    });
}
```

Note that there are two return statements within this function (I emphasized them with comments above), but they're both nested, and will not actually return a value from the invocation of `getLossCount`.

To address this, remember that our invocations against the API are all asynchronous, so if we want to get/use the data we're getting back from these calls, we have to set them up asynchronously.

So instead of something like this:
```js
this.winningStatistics.data.datasets[0].data[0] =
    getWinCount(this.nowPlaying) + this.updatedWinCount;
```

You'd do something like this:
```js
getWinCount(this.nowPlaying).then(winCount => {
    this.winningStatistics.data.datasets[0].data[0] = winCount + this.updatedWinCount;
});
```

**Comment by tmussa1** [comment]
Hello Professor,

Thank you so much professor. Following your suggestions and a little bit of
debugging, I was able to get it to work. Local storage and state management
is a life saver. I was doing it the hard way with props and events before
getting introduced to those and it was becoming a hairball. My code is much
cleaner now. I appreciate your help.

Regards,
Tofik Mussa

**Comment by susanBuck** [comment]
Hi @tmussa1 - Excellent - I'm so glad to hear you got it all sorted out. : )
