### ISSUE TITLE
"app.api.find" function return an object, but can't use Object.keys or Object.values to convert into two arrays

### ISSUE THREAD

**Issue by oscarxiao** [susanBuck/e28-spring20#80]
Hi everyone, 
I have a question about "app.api.find" function which was demonstrated in the professor's sample code of Zipfood. I am trying to further convert the object into a key array and a value array using Object.keys and Object.values, but it always return me an array of nothing. 

<img width="748" alt="Screen Shot 2020-04-26 at 9 54 44 PM" src="https://user-images.githubusercontent.com/40640721/80335541-6f344080-8809-11ea-8547-8ecda1ee388c.png">

**Comment by susanBuck** [comment]
You can't set `tempExp2` to the result of `app.api.find` and expect to get the data back - because `app.api.find` returns a Promise.

For example, if I have this code:
```js
 let example = app.api.find(
            'products',
            'name',
            'Gold Medal All Purpose Flour'
        );
        console.log(example);
```

It results in this in the console:

![image](https://user-images.githubusercontent.com/237711/80389016-9413cc80-8878-11ea-9522-1db10279cb9c.png)

Instead, you have to chain a `then` method on to the promise can capture the results within there, ex:

```js
app.api
            .find('products', 'name', 'Gold Medal All Purpose Flour')
            .then(response => {
                console.log(response);
            });
```

The above code yields this in the console:

![image](https://user-images.githubusercontent.com/237711/80389208-c7eef200-8878-11ea-905b-9b46bce52a11.png)

With the response, you can do things like find the keys:

```js
app.api
            .find('products', 'name', 'Gold Medal All Purpose Flour')
            .then(response => {
                console.log(Object.keys(response));
            });
```

![image](https://user-images.githubusercontent.com/237711/80389336-ec4ace80-8878-11ea-9373-482482550f87.png)

**Comment by susanBuck** [comment]
Follow-up: Here's a useful guide on JS promises/async methods: https://javascript.info/async

**Comment by oscarxiao** [comment]
Thank you @susanBuck
