### ISSUE TITLE
Zipfoods - Vuex data 

### ISSUE THREAD

**Issue by maqboolk** [susanBuck/e28-spring20#85]
Vuex: where can I find stored data? for eg. data for Cart.quantity

Using Local storage, I can see data in Applications tab within inspector, but using Vuex where do I see the stored data besides Vuex tab in inspector? 

Does Vuex create a file?
What will happen if I Clear History and Cache Or use incognito browser window?

**Comment by DoryAzar** [comment]
- The Vuex inspector tab is the only place where you can see that data without coding. It’s a little bit like Session data if you worked with server-side languages like PHP. The concept is the same. It’s ephemeral storage (kind of a RAM) that will disappear once the session is closed.

- Another way to see the data is to actually print it out in the console or even output it to a file if you want while in a session.

- Clearing the browser cache may have no impact at all if you are synchronizing the store with your permanent storage (file, database, local storage, noDB etc...). Of course, any non-persistent data will go away just like it would if you close the browser session.

It’s important to not confuse the Vuex store with permanent storage though. Vuex is just a « loaded » version of the data (no matter what storage it is on) that is kept live, alive and up-to-date throughout the session so that components can get the latest version of it quickly without having to fetch it from storage every time they need it.

**Comment by maqboolk** [comment]
@DoryAzar , Thank you!
