### ISSUE TITLE
Issues deploying to droplet - vue-cli-service: not found

### ISSUE THREAD

**Issue by q0w9e8r7t6y5** [susanBuck/e28-spring20#88]
Hi everyone,

I tried to follow the directions to deploy p2 to production and I keep getting this same error:

```
root@e28:/var/www/html/e28/p2# npm run build

> p2@0.1.0 build /var/www/html/e28/p2
> vue-cli-service build

sh: 1: vue-cli-service: not found

npm ERR! Linux 4.15.0-99-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! p2@0.1.0 build: `vue-cli-service build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the p2@0.1.0 build script 'vue-cli-service build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the p2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     vue-cli-service build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs p2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls p2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/e28/p2/npm-debug.log
root@e28:/var/www/html/e28/p2#

```
I have tried reinstalling npm, vue CLI, and all the requirements as per my p2 project, but still not working. Any pointers on how to solve this? I tried using stack overflow and they suggested clearing nom's cache and reinstalling, but not working!

P2 link: https://github.com/q0w9e8r7t6y5/e28/tree/master/p2

Thanks everyone!

**Comment by susanBuck** [comment]
Following the way I suggested we set things up, you don't need to run `npm run build` on your production server.

Instead, you run it locally, that generates a `/dist` folder which you then sync to production via git. Make sure you remove the `/dist` directory from your `.gitignore` file so it gets tracked.

Reference: https://hesweb.dev/e28/notes/vue/build-comprehensive#building-for-production

On a related note, to understand why you can't run `npm run build` on production I'm assuming it's because on production you're running `npm install --production` to get your dependencies. 

However, the Vue CLI services are listed under `devDependencies` so they'll only be available if you run `npm install`.

![image](https://user-images.githubusercontent.com/237711/80770246-c1cd6f80-8b1d-11ea-9b8b-25c92a6452a9.png)

Hope this above info helps; if you run into any issues trying to build locally and then deploying `/dist`, let me know.

**Comment by q0w9e8r7t6y5** [comment]
That fixed the issue! Thank you!

URL: http://e28p2.sy-e28.tech/
